/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as ProhibidasRouteImport } from './routes/prohibidas'
import { Route as PlanetRouteImport } from './routes/planet'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as LegendariasRouteImport } from './routes/legendarias'
import { Route as FloraRouteImport } from './routes/flora'
import { Route as ExpedicionesRouteImport } from './routes/expediciones'
import { Route as EcosistemasRouteImport } from './routes/ecosistemas'
import { Route as DescubrimientosRouteImport } from './routes/descubrimientos'
import { Route as ClasificacionRouteImport } from './routes/clasificacion'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as BestiaryRouteImport } from './routes/bestiary'
import { Route as ArchivoRealRouteImport } from './routes/archivo-real'
import { Route as AlquimiaRouteImport } from './routes/alquimia'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperContinentIdRouteImport } from './routes/super-continent.$id'
import { Route as NaturalIdRouteImport } from './routes/natural.$id'
import { Route as NationIdRouteImport } from './routes/nation.$id'
import { Route as MacroRegionIdRouteImport } from './routes/macro-region.$id'
import { Route as HemisphereIdRouteImport } from './routes/hemisphere.$id'
import { Route as ForbiddenIdRouteImport } from './routes/forbidden.$id'
import { Route as ContinentIdRouteImport } from './routes/continent.$id'
import { Route as CityIdRouteImport } from './routes/city.$id'

const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProhibidasRoute = ProhibidasRouteImport.update({
  id: '/prohibidas',
  path: '/prohibidas',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanetRoute = PlanetRouteImport.update({
  id: '/planet',
  path: '/planet',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const LegendariasRoute = LegendariasRouteImport.update({
  id: '/legendarias',
  path: '/legendarias',
  getParentRoute: () => rootRouteImport,
} as any)
const FloraRoute = FloraRouteImport.update({
  id: '/flora',
  path: '/flora',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedicionesRoute = ExpedicionesRouteImport.update({
  id: '/expediciones',
  path: '/expediciones',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosistemasRoute = EcosistemasRouteImport.update({
  id: '/ecosistemas',
  path: '/ecosistemas',
  getParentRoute: () => rootRouteImport,
} as any)
const DescubrimientosRoute = DescubrimientosRouteImport.update({
  id: '/descubrimientos',
  path: '/descubrimientos',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasificacionRoute = ClasificacionRouteImport.update({
  id: '/clasificacion',
  path: '/clasificacion',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryRoute = BestiaryRouteImport.update({
  id: '/bestiary',
  path: '/bestiary',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivoRealRoute = ArchivoRealRouteImport.update({
  id: '/archivo-real',
  path: '/archivo-real',
  getParentRoute: () => rootRouteImport,
} as any)
const AlquimiaRoute = AlquimiaRouteImport.update({
  id: '/alquimia',
  path: '/alquimia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperContinentIdRoute = SuperContinentIdRouteImport.update({
  id: '/super-continent/$id',
  path: '/super-continent/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NaturalIdRoute = NaturalIdRouteImport.update({
  id: '/natural/$id',
  path: '/natural/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NationIdRoute = NationIdRouteImport.update({
  id: '/nation/$id',
  path: '/nation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MacroRegionIdRoute = MacroRegionIdRouteImport.update({
  id: '/macro-region/$id',
  path: '/macro-region/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HemisphereIdRoute = HemisphereIdRouteImport.update({
  id: '/hemisphere/$id',
  path: '/hemisphere/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenIdRoute = ForbiddenIdRouteImport.update({
  id: '/forbidden/$id',
  path: '/forbidden/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContinentIdRoute = ContinentIdRouteImport.update({
  id: '/continent/$id',
  path: '/continent/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CityIdRoute = CityIdRouteImport.update({
  id: '/city/$id',
  path: '/city/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alquimia': typeof AlquimiaRoute
  '/archivo-real': typeof ArchivoRealRoute
  '/bestiary': typeof BestiaryRoute
  '/catalogo': typeof CatalogoRoute
  '/characters': typeof CharactersRoute
  '/clasificacion': typeof ClasificacionRoute
  '/descubrimientos': typeof DescubrimientosRoute
  '/ecosistemas': typeof EcosistemasRoute
  '/expediciones': typeof ExpedicionesRoute
  '/flora': typeof FloraRoute
  '/legendarias': typeof LegendariasRoute
  '/locations': typeof LocationsRoute
  '/planet': typeof PlanetRoute
  '/prohibidas': typeof ProhibidasRoute
  '/recursos': typeof RecursosRoute
  '/city/$id': typeof CityIdRoute
  '/continent/$id': typeof ContinentIdRoute
  '/forbidden/$id': typeof ForbiddenIdRoute
  '/hemisphere/$id': typeof HemisphereIdRoute
  '/macro-region/$id': typeof MacroRegionIdRoute
  '/nation/$id': typeof NationIdRoute
  '/natural/$id': typeof NaturalIdRoute
  '/super-continent/$id': typeof SuperContinentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alquimia': typeof AlquimiaRoute
  '/archivo-real': typeof ArchivoRealRoute
  '/bestiary': typeof BestiaryRoute
  '/catalogo': typeof CatalogoRoute
  '/characters': typeof CharactersRoute
  '/clasificacion': typeof ClasificacionRoute
  '/descubrimientos': typeof DescubrimientosRoute
  '/ecosistemas': typeof EcosistemasRoute
  '/expediciones': typeof ExpedicionesRoute
  '/flora': typeof FloraRoute
  '/legendarias': typeof LegendariasRoute
  '/locations': typeof LocationsRoute
  '/planet': typeof PlanetRoute
  '/prohibidas': typeof ProhibidasRoute
  '/recursos': typeof RecursosRoute
  '/city/$id': typeof CityIdRoute
  '/continent/$id': typeof ContinentIdRoute
  '/forbidden/$id': typeof ForbiddenIdRoute
  '/hemisphere/$id': typeof HemisphereIdRoute
  '/macro-region/$id': typeof MacroRegionIdRoute
  '/nation/$id': typeof NationIdRoute
  '/natural/$id': typeof NaturalIdRoute
  '/super-continent/$id': typeof SuperContinentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alquimia': typeof AlquimiaRoute
  '/archivo-real': typeof ArchivoRealRoute
  '/bestiary': typeof BestiaryRoute
  '/catalogo': typeof CatalogoRoute
  '/characters': typeof CharactersRoute
  '/clasificacion': typeof ClasificacionRoute
  '/descubrimientos': typeof DescubrimientosRoute
  '/ecosistemas': typeof EcosistemasRoute
  '/expediciones': typeof ExpedicionesRoute
  '/flora': typeof FloraRoute
  '/legendarias': typeof LegendariasRoute
  '/locations': typeof LocationsRoute
  '/planet': typeof PlanetRoute
  '/prohibidas': typeof ProhibidasRoute
  '/recursos': typeof RecursosRoute
  '/city/$id': typeof CityIdRoute
  '/continent/$id': typeof ContinentIdRoute
  '/forbidden/$id': typeof ForbiddenIdRoute
  '/hemisphere/$id': typeof HemisphereIdRoute
  '/macro-region/$id': typeof MacroRegionIdRoute
  '/nation/$id': typeof NationIdRoute
  '/natural/$id': typeof NaturalIdRoute
  '/super-continent/$id': typeof SuperContinentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alquimia'
    | '/archivo-real'
    | '/bestiary'
    | '/catalogo'
    | '/characters'
    | '/clasificacion'
    | '/descubrimientos'
    | '/ecosistemas'
    | '/expediciones'
    | '/flora'
    | '/legendarias'
    | '/locations'
    | '/planet'
    | '/prohibidas'
    | '/recursos'
    | '/city/$id'
    | '/continent/$id'
    | '/forbidden/$id'
    | '/hemisphere/$id'
    | '/macro-region/$id'
    | '/nation/$id'
    | '/natural/$id'
    | '/super-continent/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alquimia'
    | '/archivo-real'
    | '/bestiary'
    | '/catalogo'
    | '/characters'
    | '/clasificacion'
    | '/descubrimientos'
    | '/ecosistemas'
    | '/expediciones'
    | '/flora'
    | '/legendarias'
    | '/locations'
    | '/planet'
    | '/prohibidas'
    | '/recursos'
    | '/city/$id'
    | '/continent/$id'
    | '/forbidden/$id'
    | '/hemisphere/$id'
    | '/macro-region/$id'
    | '/nation/$id'
    | '/natural/$id'
    | '/super-continent/$id'
  id:
    | '__root__'
    | '/'
    | '/alquimia'
    | '/archivo-real'
    | '/bestiary'
    | '/catalogo'
    | '/characters'
    | '/clasificacion'
    | '/descubrimientos'
    | '/ecosistemas'
    | '/expediciones'
    | '/flora'
    | '/legendarias'
    | '/locations'
    | '/planet'
    | '/prohibidas'
    | '/recursos'
    | '/city/$id'
    | '/continent/$id'
    | '/forbidden/$id'
    | '/hemisphere/$id'
    | '/macro-region/$id'
    | '/nation/$id'
    | '/natural/$id'
    | '/super-continent/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlquimiaRoute: typeof AlquimiaRoute
  ArchivoRealRoute: typeof ArchivoRealRoute
  BestiaryRoute: typeof BestiaryRoute
  CatalogoRoute: typeof CatalogoRoute
  CharactersRoute: typeof CharactersRoute
  ClasificacionRoute: typeof ClasificacionRoute
  DescubrimientosRoute: typeof DescubrimientosRoute
  EcosistemasRoute: typeof EcosistemasRoute
  ExpedicionesRoute: typeof ExpedicionesRoute
  FloraRoute: typeof FloraRoute
  LegendariasRoute: typeof LegendariasRoute
  LocationsRoute: typeof LocationsRoute
  PlanetRoute: typeof PlanetRoute
  ProhibidasRoute: typeof ProhibidasRoute
  RecursosRoute: typeof RecursosRoute
  CityIdRoute: typeof CityIdRoute
  ContinentIdRoute: typeof ContinentIdRoute
  ForbiddenIdRoute: typeof ForbiddenIdRoute
  HemisphereIdRoute: typeof HemisphereIdRoute
  MacroRegionIdRoute: typeof MacroRegionIdRoute
  NationIdRoute: typeof NationIdRoute
  NaturalIdRoute: typeof NaturalIdRoute
  SuperContinentIdRoute: typeof SuperContinentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prohibidas': {
      id: '/prohibidas'
      path: '/prohibidas'
      fullPath: '/prohibidas'
      preLoaderRoute: typeof ProhibidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planet': {
      id: '/planet'
      path: '/planet'
      fullPath: '/planet'
      preLoaderRoute: typeof PlanetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legendarias': {
      id: '/legendarias'
      path: '/legendarias'
      fullPath: '/legendarias'
      preLoaderRoute: typeof LegendariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flora': {
      id: '/flora'
      path: '/flora'
      fullPath: '/flora'
      preLoaderRoute: typeof FloraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expediciones': {
      id: '/expediciones'
      path: '/expediciones'
      fullPath: '/expediciones'
      preLoaderRoute: typeof ExpedicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosistemas': {
      id: '/ecosistemas'
      path: '/ecosistemas'
      fullPath: '/ecosistemas'
      preLoaderRoute: typeof EcosistemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descubrimientos': {
      id: '/descubrimientos'
      path: '/descubrimientos'
      fullPath: '/descubrimientos'
      preLoaderRoute: typeof DescubrimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clasificacion': {
      id: '/clasificacion'
      path: '/clasificacion'
      fullPath: '/clasificacion'
      preLoaderRoute: typeof ClasificacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary': {
      id: '/bestiary'
      path: '/bestiary'
      fullPath: '/bestiary'
      preLoaderRoute: typeof BestiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archivo-real': {
      id: '/archivo-real'
      path: '/archivo-real'
      fullPath: '/archivo-real'
      preLoaderRoute: typeof ArchivoRealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alquimia': {
      id: '/alquimia'
      path: '/alquimia'
      fullPath: '/alquimia'
      preLoaderRoute: typeof AlquimiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-continent/$id': {
      id: '/super-continent/$id'
      path: '/super-continent/$id'
      fullPath: '/super-continent/$id'
      preLoaderRoute: typeof SuperContinentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/natural/$id': {
      id: '/natural/$id'
      path: '/natural/$id'
      fullPath: '/natural/$id'
      preLoaderRoute: typeof NaturalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nation/$id': {
      id: '/nation/$id'
      path: '/nation/$id'
      fullPath: '/nation/$id'
      preLoaderRoute: typeof NationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macro-region/$id': {
      id: '/macro-region/$id'
      path: '/macro-region/$id'
      fullPath: '/macro-region/$id'
      preLoaderRoute: typeof MacroRegionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hemisphere/$id': {
      id: '/hemisphere/$id'
      path: '/hemisphere/$id'
      fullPath: '/hemisphere/$id'
      preLoaderRoute: typeof HemisphereIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden/$id': {
      id: '/forbidden/$id'
      path: '/forbidden/$id'
      fullPath: '/forbidden/$id'
      preLoaderRoute: typeof ForbiddenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/continent/$id': {
      id: '/continent/$id'
      path: '/continent/$id'
      fullPath: '/continent/$id'
      preLoaderRoute: typeof ContinentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$id': {
      id: '/city/$id'
      path: '/city/$id'
      fullPath: '/city/$id'
      preLoaderRoute: typeof CityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlquimiaRoute: AlquimiaRoute,
  ArchivoRealRoute: ArchivoRealRoute,
  BestiaryRoute: BestiaryRoute,
  CatalogoRoute: CatalogoRoute,
  CharactersRoute: CharactersRoute,
  ClasificacionRoute: ClasificacionRoute,
  DescubrimientosRoute: DescubrimientosRoute,
  EcosistemasRoute: EcosistemasRoute,
  ExpedicionesRoute: ExpedicionesRoute,
  FloraRoute: FloraRoute,
  LegendariasRoute: LegendariasRoute,
  LocationsRoute: LocationsRoute,
  PlanetRoute: PlanetRoute,
  ProhibidasRoute: ProhibidasRoute,
  RecursosRoute: RecursosRoute,
  CityIdRoute: CityIdRoute,
  ContinentIdRoute: ContinentIdRoute,
  ForbiddenIdRoute: ForbiddenIdRoute,
  HemisphereIdRoute: HemisphereIdRoute,
  MacroRegionIdRoute: MacroRegionIdRoute,
  NationIdRoute: NationIdRoute,
  NaturalIdRoute: NaturalIdRoute,
  SuperContinentIdRoute: SuperContinentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
